# Wave 38 - mindrally / aj-geddes / bobmatnyc / tech-leads / antigravity 补装
# 补跑脚本: install-fullstack-skills-wave38-resume.ps1
# 注意: aj-geddes 部分技能 CLI 名为带空格标题（如 "A/B Test Analysis"），文件夹为 kebab-case
$ErrorActionPreference = "Continue"
. (Join-Path $PSScriptRoot "github-mirror.ps1")
Enable-GitHubMirror
$HubDir = Split-Path $PSScriptRoot -Parent
$logDir = Join-Path $HubDir "logs"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$summaryFile = Join-Path $logDir "fullstack-wave38-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
function Run-SkillBatch {
    param([string]$Label, [string]$Repo, [string[]]$Skills, [switch]$All)
    $r = Invoke-SkillInstall -Label $Label -Repo $Repo -Skills $Skills -All:$All -LogDir $logDir -LogPrefix "wave38"
    if ($r.Ok) { "OK  $Label" | Tee-Object -FilePath $summaryFile -Append; return $true }
    "FAIL $Label" | Tee-Object -FilePath $summaryFile -Append; return $false
}
"Fullstack Wave 38 started at $(Get-Date)" | Tee-Object -FilePath $summaryFile
Run-SkillBatch -Label "mindrally-1" -Repo "https://github.com/mindrally/skills" -Skills @("alpine-js","analytics-data-analysis","anime-js","anthropic-claude-development","api-development","aspnet-core","auth0-authentication","autogen-development","azure","beautifulsoup-parsing","bitbucket-workflow","blockchain","bootstrap","business-central-development","cheerio-parsing","chrome-extension-development","clerk-authentication","computer-vision-opencv","convex","cpp","c-sharp","css","data-analysis-jupyter","data-analyst","deep-learning","drizzle-orm","ethereum","fpga","framer-motion","front-end-developer","game-development","general-best-practices","ghost","github-workflow","gitlab-workflow","go","graalvm","gsap","html","htmx")

Run-SkillBatch -Label "mindrally-2" -Repo "https://github.com/mindrally/skills" -Skills @("internationalization-i18n","ionic","jax-best-practices","julia","koa-typescript","kotlin-development","kysely","langchain-development","laravel","laravel-development","lerna","less-best-practices","llamaindex-development","llm","localization-l10n","lottie","machine-learning","matplotlib-best-practices","meta-prompt","micronaut","microservices","modern-web-development","mongodb-development","monitoring-guidelines","monorepo","monorepo-tamagui","motion","mqtt-development","mysql-best-practices","nestjs-clean-typescript","netlify-development","nextauth-authentication","nextjs-react-redux-typescript-cursor-rules","nextjs-react-typescript","nextjs-typescript-tailwindcss-supabase","nlp-natural-language-processing","nodejs-development","numpy-best-practices","nuxtjs-vue-typescript","nx")

Run-SkillBatch -Label "mindrally-3" -Repo "https://github.com/mindrally/skills" -Skills @("oauth-implementation","observability-guidelines","odoo-development","onchainkit","openai-api-development","optimized-nextjs-typescript","pandas-best-practices","parcel-bundler","php-development","pixi-js","playwright-cursor-rules","postcss-best-practices","postgresql-best-practices","prisma","prisma-development","pwa-development","python","python-cybersecurity-tool-development","python-odoo-cursor-rules","python-uv","pytorch","quarkus","react","react-native-cursor-rules","react-native-r3f","react-query","redis-best-practices","redux-toolkit","remix","rest-api-django","robocorp-cursor-rules","rollup-bundler","rspec","ruby","rust","salesforce-development","salesforce-dx","sanity","sass-best-practices","scikit-learn-best-practices")

Run-SkillBatch -Label "mindrally-4" -Repo "https://github.com/mindrally/skills" -Skills @("scipy-best-practices","scrapy-web-scraping","scss-best-practices","seo-best-practices","sequelize","serverless","shopify","shopify-theme-development-guidelines","solana","solidity","spring-framework","sql-best-practices","stripe","styled-components-best-practices","supabase-development","swift","swiftui-development","swr","systemverilog","tailwindcss","tanstack-query","tauri-development","technical-writing","three-js","transformers-huggingface","turbopack-bundler","typeorm","typescript","ui-design","unity","ux-design","vercel-development","viewcomfy-api-rules","vite","vuejs-typescript-best-practices","vue-typescript","web-development","webpack-bundler","web-scraping","websocket-development")

Run-SkillBatch -Label "mindrally-5" -Repo "https://github.com/mindrally/skills" -Skills @("woocommerce","wordpress","zustand-state-management")

Run-SkillBatch -Label "ajgeddes-1" -Repo "https://github.com/aj-geddes/useful-ai-prompts" -Skills @("ab-test-analysis","anomaly-detection","business-case-development","capacity-planning","causal-inference","changelog-maintenance","classification-modeling","cloud-migration-planning","cloud-storage-optimization","clustering-analysis","code-generation-template","code-metrics-analysis","code-review-analysis","cohort-analysis","color-accessibility","competitor-analysis","computer-vision","correlation-analysis","cpu-profiling","cross-platform-compatibility","csrf-protection","css-architecture","data-cleaning-pipeline","data-encryption","data-migration-scripts","data-replication-setup","design-handoff","design-patterns-implementation","design-system-creation","developer-onboarding","dimensionality-reduction","dns-management","documentation-site-setup","email-service-integration","event-sourcing","exploratory-data-analysis","fastapi-development","feature-engineering","file-upload-handling","flutter-development")

Run-SkillBatch -Label "ajgeddes-2" -Repo "https://github.com/aj-geddes/useful-ai-prompts" -Skills @("form-validation","frontend-accessibility","frontend-routing","frontend-state-management","frontend-testing","funnel-analysis","gap-analysis","gcp-cloud-functions","git-hooks-setup","github-actions-workflow","gitlab-cicd-pipeline","git-workflow-strategy","graceful-shutdown","grafana-dashboard","graphql-implementation","grpc-service-development","idempotency-handling","image-optimization","incident-response-plan","information-architecture","infrastructure-cost-optimization","infrastructure-monitoring","integration-testing","intermittent-issue-debugging","internationalization-i18n","ios-swift-development","jenkins-pipeline","load-balancer-setup","log-aggregation","log-analysis","memory-leak-detection","memory-optimization","microservices-architecture","ml-model-explanation","ml-model-training","ml-pipeline-automation","mobile-app-debugging","mobile-app-testing","mobile-first-design","mobile-offline-support")

Run-SkillBatch -Label "ajgeddes-3" -Repo "https://github.com/aj-geddes/useful-ai-prompts" -Skills @("mocking-stubbing","model-deployment","model-hyperparameter-tuning","model-monitoring","multi-cloud-strategy","natural-language-processing","network-analysis","network-debugging","network-security-groups","neural-network-design","nginx-configuration","nodejs-express-server","nosql-database-design","oauth-implementation","payment-gateway-integration","performance-regression-debugging","performance-testing","polyglot-integration","process-mapping","profiling-optimization","progressive-web-app","project-estimation","prometheus-monitoring","pull-request-automation","push-notification-setup","query-caching-strategies","rate-limiting-implementation","react-component-architecture","reactive-programming","react-native-app","real-time-features","recommendation-engine","recommendation-system","refactor-legacy-code","regression-modeling","release-planning","requirements-gathering","responsive-web-design","retrospective-facilitation","risk-assessment")

Run-SkillBatch -Label "ajgeddes-4" -Repo "https://github.com/aj-geddes/useful-ai-prompts" -Skills @("root-cause-analysis","secrets-rotation","security-audit-logging","security-compliance-audit","security-documentation","security-headers-configuration","security-testing","semantic-versioning","sentiment-analysis","serverless-architecture","server-side-rendering","session-management","spring-boot-application","sql-injection-prevention","sql-query-optimization","ssl-certificate-management","stakeholder-communication","static-code-analysis","statistical-hypothesis-testing","stored-procedures","stress-testing","survival-analysis","synthetic-monitoring","technical-debt-assessment","technical-roadmap-planning","test-automation-framework","test-data-generation","third-party-integration","time-series-analysis","transaction-management","troubleshooting-guide","unit-testing-framework","uptime-monitoring","user-guide-creation","user-persona-creation","user-research-analysis","user-story-writing","visual-regression-testing","vue-application-structure","vulnerability-scanning")

Run-SkillBatch -Label "ajgeddes-5" -Repo "https://github.com/aj-geddes/useful-ai-prompts" -Skills @("webhook-development","webhook-integration","web-performance-audit","websocket-implementation","wireframe-prototyping","xss-prevention","zero-trust-architecture")

Run-SkillBatch -Label "bobmatnyc-1" -Repo "https://github.com/bobmatnyc/claude-mpm-skills" -Skills @("anthropic","api-design-patterns","api-documentation","api-review","artifacts-builder","asyncio","axum","bad-interdependent-skill","better-auth-authentication","better-auth-core","better-auth-integrations","better-auth-plugins","bug-fix","cargo-release","celery","clap","code-production-process","code-quality-scoring","code-review-standards","condition-based-waiting","daisyui","datadog","dependency-audit","desktop-applications","digitalocean-agentic-cloud","digitalocean-compute","digitalocean-containers-images","digitalocean-managed-databases","digitalocean-management","digitalocean-networking","digitalocean-overview","digitalocean-storage","digitalocean-teams","django","drizzle","drizzle-migrations")

Run-SkillBatch -Label "bobmatnyc-2" -Repo "https://github.com/bobmatnyc/claude-mpm-skills" -Skills @("dspy","ecto-patterns","emergency-release-workflow","env-manager","espocrm","fastapi-local-dev","fastify","flask","gh-cli","github-actions","good-self-contained-skill","headlessui","homebrew-formula-maintenance","internal-comms","json-data-handling","kysely","langchain","local-llm-ops","mcp","media-transcoding","mongodb","mpm-orchestration-demo","mypy","netlify","nextjs-core","nextjs-v16","nodejs-backend","openrouter","pre-merge","prisma","pr-quality-checklist","pydantic","pyright","pytest","reporting-pipelines","rust-quality-gate")

Run-SkillBatch -Label "bobmatnyc-3" -Repo "https://github.com/bobmatnyc/claude-mpm-skills" -Skills @("screenshot","sec-edgar-pipeline","security-scanning","session-compression","software-patterns","sqlalchemy","stacked-prs","tailwind","tanstack-query","tauri","testing-anti-patterns","test-quality-inspector","threat-modeling","typescript-core","validated-handler","vb6-legacy","vb-core","vb-database","vb-winforms","vector-search-workflows","vercel-ai","vercel-deployments-builds","vercel-functions-runtime","vercel-networking-domains","vercel-observability","vercel-overview","vercel-security-access","vercel-storage-data","vercel-teams-billing","vite","wordpress-advanced-architecture","wordpress-block-editor-fse","wordpress-security-validation","wordpress-testing-qa","xlsx","zustand")

Run-SkillBatch -Label "techleads-remaining" -Repo "https://github.com/tech-leads-club/agent-skills" -Skills @("ai-cold-outreach","ai-pricing","ai-sdr","ai-ugc-ads","codenavi","create-technical-design-doc","expansion-retention","gtm-engineering","gtm-metrics","lead-enrichment","legacy-migration-planner","mermaid-studio","modular-design-principles","multi-platform-launch","nestjs-modular-monolith","nx-ci-monitor","nx-generate","nx-run-tasks","nx-workspace","paid-creative-ai","partner-affiliate","perf-astro","perf-lighthouse","perf-web-optimization","positioning-icp","react-best-practices","react-composition-patterns","render-deploy","sales-motion-design","security-ownership-map","shopify-developer","skill-architect","social-selling","solo-founder-gtm","spec-driven-eval","subagent-creator","tactical-ddd","tlc-spec-driven","video-outreach","web-accessibility","web-best-practices","web-quality-audit")

Run-SkillBatch -Label "antigravity-dev" -Repo "https://github.com/sickn33/antigravity-awesome-skills" -Skills @("accessibility-compliance-accessibility-audit","android-ui-journey-testing","api-testing-observability-api-mock","application-performance-performance-optimization","app-store-changelog","app-store-optimization","awt-e2e-testing","azd-deployment","backend-architect","bash-linux","bash-pro","browser-extension-builder","chrome-extension-developer","code-review-ai-ai-review","code-review-checklist","container-security-hardening","copilot-sdk","create-branch","create-issue-gate","debug-buttercup","dependency-management-deps-audit","design-it","design-orchestration","design-spells","design-taste-frontend","devcontainer-setup","devops-deploy","devops-troubleshooter","django-access-review","django-perf-review","docs-architect","email-sequence","email-systems","error-debugging-error-analysis","error-debugging-error-trace")
"`nWave 38 done at $(Get-Date)" | Tee-Object -FilePath $summaryFile -Append
Write-Host "`nWave 38 complete: $summaryFile" -ForegroundColor Green
